### PR TITLE
Provisioning PostgreSQL

### PR DESCRIPTION
**Pull request by ebenezergraham**

### CODE REVIEW

**Comment by ebenezergraham** [comment]
@Izakey I just noticed that I we didn't merge the work done in demo-server. 

Please merge this with your demo-server

**Comment by Izakey** [comment]
Okay @ebenezergraham , I've taken a closer look at this and it looks good.

**Review by Izakey — APPROVED** [review]
Changes Look Good ! Lines 218-223 provide for connections to PostgreSQL database.

**Comment by Izakey** [comment]
@ebenezergraham  Done !

**Pull request merged**
